### ISSUE TITLE
build: no ocrd-0.1-jar-with-dependencies.jar

### ISSUE THREAD

**Issue by jbarth-ubhd** [cisocrgroup/ocrd-postcorrection#9]
Tried with Eclipse 2022-03 & Spring Tools 4.15.2.RELEASE :

```
...
Run from new projects's context menu Maven->Update project
New Java code from RAML is generated in /target/generated-sources/raml-jaxrs
```

There is no directory _raml-jaxrs_ after running this steps,
also no _target/ocrd-0.1-jar-with-dependencies.jar_ (no jar at all, but **0** errors).

Eclipse export to _Runnable JAR file_ is not possible due to lacking _Launch configuration_.

_Maven Build→ocrd-postcorrection_ complains _No goals have been specified for this build_,
don't know how to configure _Spring Boot App_ in _Run Configurations_ (if necessarry).

**Comment by jbarth-ubhd** [comment]
`mvn package` says
```
...
Failed tests:   testIds(de.lmu.cis.ocrd.ocropus.test.WorkspaceTest): (..)

Tests run: 277, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:05 min
[INFO] Finished at: 2022-08-10T13:13:15+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project ocrd: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/jb/ocrd-postcorrection/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

```
-------------------------------------------------------------------------------
Test set: de.lmu.cis.ocrd.ocropus.test.WorkspaceTest
-------------------------------------------------------------------------------
Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.059 sec <<< FAILURE!
testIds(de.lmu.cis.ocrd.ocropus.test.WorkspaceTest)  Time elapsed: 0.022 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is "1"
     but: was "0001.llocs.1:1"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:964)
        at org.junit.Assert.assertThat(Assert.java:930)
        at de.lmu.cis.ocrd.ocropus.test.WorkspaceTest.testIds(WorkspaceTest.java:93)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
...
```
